import React, { useEffect, useState } from 'react'
import { NavLink } from 'react-router-dom'
import { useAuth } from '../../auth'
import { getSystemStatus, listCases } from '../../services/api'

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => <div style={{ marginBottom: 18 }}><div style={{ fontSize: 10, letterSpacing: '0.1em', fontWeight: 700, color: 'var(--text-3)', padding: '0 16px 8px', textTransform: 'uppercase' }}>{title}</div><div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>{children}</div></div>
const Item = ({ to, icon, label, badge, end, onNavigate }: { to: string; icon: string; label: string; badge?: number | string; end?: boolean; onNavigate: () => void }) => <NavLink to={to} end={end} onClick={onNavigate} style={({ isActive }) => ({ display: 'flex', alignItems: 'center', gap: 10, padding: '8px 12px', margin: '0 8px', borderRadius: 8, fontSize: 12, fontWeight: isActive ? 700 : 500, letterSpacing: '0.02em', background: isActive ? 'rgba(34,211,238,0.10)' : 'transparent', border: isActive ? '1px solid rgba(34,211,238,0.2)' : '1px solid transparent', color: isActive ? 'var(--text-1)' : 'var(--text-2)' })}><span style={{ width: 18, textAlign: 'center', fontSize: 13 }}>{icon}</span><span style={{ flex: 1 }}>{label}</span>{badge !== undefined && <span style={{ fontSize: 10, fontWeight: 700, background: 'var(--bg-elevated)', border: '1px solid var(--border)', padding: '2px 6px', borderRadius: 99, color: 'var(--text-2)' }}>{badge}</span>}</NavLink>

export function Sidebar({ collapsed, onToggle }: { collapsed: boolean; onToggle: () => void }) {
  const { session } = useAuth()
  const [caseCount, setCaseCount] = useState<number | null>(null)
  const [systemStatus, setSystemStatus] = useState('unknown')
  const investigator = session?.investigator
  const name = investigator?.full_name || investigator?.investigator_id || 'Investigator'
  const initials = name.split(/\s+/).map(part => part[0]).join('').slice(0, 2).toUpperCase()

  const closeOnMobile = () => { if (window.matchMedia('(max-width: 1024px)').matches) onToggle() }

  useEffect(() => {
    let active = true
    listCases({ limit: 1 }).then(cases => { if (active) setCaseCount(cases.total) }).catch(() => undefined)
    getSystemStatus().then(status => { if (active) setSystemStatus(status.overall) }).catch(() => { if (active) setSystemStatus('offline') })
    return () => { active = false }
  }, [])

  return <aside className={collapsed ? 'collapsed' : undefined} style={{ width: 260, minWidth: 260, background: 'linear-gradient(180deg, #0a0f1e 0%, #0d1528 100%)', borderRight: '1px solid var(--border)', display: 'flex', flexDirection: 'column', height: '100vh', position: 'sticky', top: 0, overflow: 'hidden' }}>
    <div style={{ padding: '18px 16px 14px', borderBottom: '1px solid var(--border)', background: 'rgba(255,255,255,0.02)' }}><div style={{ display: 'flex', alignItems: 'center', gap: 10 }}><div style={{ width: 34, height: 34, borderRadius: 8, background: 'linear-gradient(135deg,#06b6d4,#3b82f6)', display: 'grid', placeItems: 'center', fontWeight: 800, fontSize: 12, color: 'white', letterSpacing: '0.06em' }}>AT</div><div><div style={{ fontWeight: 800, fontSize: 13, letterSpacing: '0.08em', lineHeight: 1 }}>DARKTRACE <span style={{ color: 'var(--accent)' }}>AI</span></div><div style={{ fontSize: 10, letterSpacing: '0.14em', color: 'var(--text-3)', fontWeight: 700 }}>ATLAS • DEANONYMIZATION WORKSTATION</div></div></div><div style={{ marginTop: 12, display: 'flex', gap: 6, flexWrap: 'wrap' }}><span style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.06em', background: 'var(--accent-dim)', border: '1px solid var(--accent-border)', color: 'var(--accent)', padding: '3px 8px', borderRadius: 99 }}>CLEARANCE L{session?.clearance_level ?? investigator?.clearance_level ?? '?'}</span><span className={`status-chip ${['healthy', 'operational', 'connected'].includes(systemStatus.toLowerCase()) ? 'status-chip-ok' : ''}`}><span className="status-dot" />{systemStatus.toUpperCase()}</span></div></div>
    <div style={{ flex: 1, overflowY: 'auto', padding: '14px 0' }} className="no-scrollbar"><Section title="Investigation"><Item to="/" icon="◈" label="Attribution Console" end onNavigate={closeOnMobile} /><Item to="/cases" icon="▭" label="Attribution Investigations" badge={caseCount ?? '—'} onNavigate={closeOnMobile} /><Item to="/workspace" icon="◎" label="Deanonymization Workspace" onNavigate={closeOnMobile} /><Item to="/evidence" icon="⬢" label="Evidence & Artifacts" onNavigate={closeOnMobile} /><Item to="/intelligence" icon="⬣" label="Authorized Collection" onNavigate={closeOnMobile} /></Section><Section title="Analysis"><Item to="/analysis" icon="⬔" label="Attribution Signals" onNavigate={closeOnMobile} /><Item to="/entities" icon="⬙" label="Identity Candidates" onNavigate={closeOnMobile} /><Item to="/graph" icon="⬡" label="Identity Linkage Graph" onNavigate={closeOnMobile} /><Item to="/confidence" icon="◐" label="Attribution Confidence" onNavigate={closeOnMobile} /></Section><Section title="Operations"><Item to="/review" icon="⧉" label="Analyst Verification" onNavigate={closeOnMobile} /><Item to="/reports" icon="▤" label="Attribution Reports" onNavigate={closeOnMobile} /><Item to="/timeline" icon="◷" label="Attribution Timeline" onNavigate={closeOnMobile} /></Section></div>
    <div style={{ padding: 12, borderTop: '1px solid var(--border)', background: 'rgba(255,255,255,0.02)' }}><div style={{ display: 'flex', gap: 10, alignItems: 'center', background: 'var(--bg-soft)', border: '1px solid var(--border)', borderRadius: 10, padding: '10px 12px' }}><div style={{ width: 32, height: 32, borderRadius: 999, background: '#1e293b', display: 'grid', placeItems: 'center', fontWeight: 700, color: 'var(--accent)', border: '1px solid var(--border)' }}>{initials}</div><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontWeight: 700, fontSize: 12, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{name}</div><div style={{ fontSize: 11, color: 'var(--text-3)', fontFamily: 'var(--mono)' }}>{investigator?.investigator_id || 'No investigator ID'}</div></div><span className="kbd">L{session?.clearance_level ?? '?'}</span></div><div style={{ marginTop: 8, fontSize: 10, color: 'var(--text-3)', textAlign: 'center', letterSpacing: '0.04em' }}>AUTHENTICATED SESSION • SYNTHETIC DATASET</div></div>
  </aside>
}
