import { useCaseData, toCaseViewModel } from '../hooks/useCaseData'
import { useSelectedCaseId } from '../hooks/useSelectedCaseId'
import { Panel } from '../components/common/Panel'
import { Badge } from '../components/common/Badge'
import { EmptyState, ErrorState, LoadingState } from '../components/common/AsyncState'

export function Intelligence() {
  const { caseId } = useSelectedCaseId()
  const state = useCaseData(caseId)
  if (!caseId) return <LoadingState label="Selecting a case from the backend…" />
  if (state.loading || !state.data) return state.error ? <ErrorState message={state.error} onRetry={state.reload} /> : <LoadingState label="Loading intelligence jobs…" />
  const jobs = toCaseViewModel(state.data).intelligence
  const counts = ['ready', 'running', 'completed'].map(status => ({ status, count: jobs.filter(job => job.status === status).length }))
  return <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 12 }}><div><div style={{ fontSize: 20, fontWeight: 800 }}>Authorized Dark-Web Collection</div><div className="mono" style={{ fontSize: 11, color: 'var(--text-3)' }}>Live collection jobs for {caseId} • Sources must be authorized before ingestion</div></div><button className="btn" onClick={() => state.reload()}>Refresh jobs</button></div><div className="grid grid-3">{counts.map(item => <div key={item.status} className="panel" style={{ padding: 14 }}><div style={{ fontSize: 10, color: 'var(--text-3)', letterSpacing: '0.08em' }}>{item.status.toUpperCase()}</div><div className="mono" style={{ fontSize: 24, fontWeight: 800, marginTop: 4 }}>{item.count}</div></div>)}</div><Panel title="Authorized collection jobs"><div className="table-wrap"><table><thead><tr><th>JOB ID</th><th>SOURCE</th><th>TYPE</th><th>STATUS</th><th>PROGRESS</th><th>STARTED</th><th>RESULTS</th><th>AUTHORIZED BY</th></tr></thead><tbody>{jobs.map(job => <tr key={job.job_id}><td className="mono">{job.job_id}</td><td style={{ fontWeight: 700 }}>{job.source}</td><td className="mono">{job.job_type}</td><td><Badge tone={job.status === 'completed' ? 'success' : job.status === 'failed' ? 'danger' : job.status === 'requires_review' ? 'violet' : 'warn'}>{job.status.replace(/_/g, ' ').toUpperCase()}</Badge></td><td><div style={{ display: 'flex', gap: 7, alignItems: 'center' }}><div className="progress-track" style={{ width: 80 }}><div className="progress-fill" style={{ width: `${job.progress}%` }} /></div><span className="mono">{job.progress}%</span></div></td><td className="mono">{job.started_at ? new Date(job.started_at).toLocaleString() : '—'}</td><td className="mono">{job.results}</td><td className="mono">{job.authorized_by || '—'}</td></tr>)}{!jobs.length && <tr><td colSpan={8}><EmptyState label="No intelligence jobs returned for this case." /></td></tr>}</tbody></table></div><div style={{ marginTop: 10, fontSize: 11, color: 'var(--text-3)' }}>Collection actions are read-only here because the backend currently exposes the case intelligence GET endpoint; source authorization remains an explicit server-side responsibility.</div></Panel></div>
}
