import { Panel } from '../components/common/Panel'
import { Badge } from '../components/common/Badge'
import { EmptyState, ErrorState, LoadingState } from '../components/common/AsyncState'
import { toCaseViewModel, useCaseData } from '../hooks/useCaseData'
import { useSelectedCaseId } from '../hooks/useSelectedCaseId'

export function Timeline() {
  const { caseId } = useSelectedCaseId()
  const state = useCaseData(caseId)
  if (!caseId) return <LoadingState label="Selecting a case from the backend…" />
  if (state.loading || !state.data) return state.error ? <ErrorState message={state.error} onRetry={state.reload} /> : <LoadingState label="Loading timeline and audit data…" />
  const vm = toCaseViewModel(state.data)
  return <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><div><div style={{ fontSize: 20, fontWeight: 800 }}>Attribution Timeline & Audit</div><div className="mono" style={{ fontSize: 11, color: 'var(--text-3)' }}>Live temporal evidence and audit records for {caseId}</div></div><button className="btn" onClick={() => state.reload()}>Refresh</button></div><div className="grid" style={{ gridTemplateColumns: '1.2fr 0.8fr' }}><Panel title="Anonymous-actor activity timeline"><div style={{ display: 'grid', gap: 10 }}>{vm.timeline.map(event => <div key={event.event_id} style={{ display: 'flex', gap: 10, background: 'var(--bg-soft)', border: '1px solid var(--border)', borderRadius: 10, padding: '10px 12px' }}><div className="mono" style={{ color: 'var(--accent)', fontSize: 11, minWidth: 150 }}>{new Date(event.timestamp).toLocaleString()}</div><div style={{ flex: 1 }}><div style={{ display: 'flex', gap: 7, flexWrap: 'wrap' }}><strong>{event.title}</strong><Badge tone="info">{event.type}</Badge><Badge tone="neutral">{event.source}</Badge></div><div style={{ fontSize: 11, color: 'var(--text-3)', marginTop: 4 }}>{event.description}{event.evidence_ids && <span className="mono" style={{ color: 'var(--accent)' }}> • {event.evidence_ids}</span>}</div></div></div>)}{!vm.timeline.length && <EmptyState label="No timeline events returned for this case." />}</div></Panel><Panel title="Attribution audit log" actions={<Badge tone="neutral">AUDITED</Badge>}><div style={{ display: 'grid', gap: 8 }}>{vm.audit.map(event => <div key={event.event_id} style={{ background: 'var(--bg-soft)', border: '1px solid var(--border)', borderRadius: 8, padding: '10px 12px' }}><div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}><span className="mono" style={{ fontSize: 11 }}>{new Date(event.created_at).toLocaleString()}</span><Badge tone="violet">{event.event_type}</Badge></div><div style={{ fontWeight: 600, marginTop: 4 }}>{event.description || 'No description.'}</div></div>)}{!vm.audit.length && <EmptyState label="No audit events returned for this case." />}</div></Panel></div></div>
}
